### ISSUE TITLE
Cannot read property 'setBadge' of undefined - on Windows

### ISSUE THREAD

**Issue by gfpacheco** [skewedlines/Nativefier#3]
You're using the `app.dock` even though it's not supported on Windows.
I ran the nativefier only for win32 platform and when the app regain focus it throws an error:

    Uncaught Exception:
    TypeError: Cannot read property 'setBadge' of undefined
        at BrowserWindow.<anonymous>
    (...\resources\app\main.js:44:17)
        at emitOne (events.js:82:20)
        at BrowserWindow.emit (event.js:169:7)

I imagine a single `if (process.platform === 'darwin')` must solve the issue, just reporting.

BTW, great project!

**Comment by skewedlines** [comment]
#4 That makes sense, thanks!
